image: "docker:19.03.5"

stages:
  - build
  - push
  - clean

services:
  - docker:dind

before_script:
  - docker info
  #- export HTTP_PROXY="http://proxy-ip:port"
  #- export HTTPS_PROXY="http://proxy-ip:port"
  - apk add make

build:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  stage: build
  script:
    - make build

push:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TAG'
      when: on_success
  stage: push
  script:
    - make push

clean:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
  stage: cleanimages
  script:
    - make clean

